### ISSUE TITLE
index.ts is missing from TypeScript compilation

### ISSUE THREAD

**Issue by jcollard** [arthurvaverko/ngx-fill-height#2]
I just upgraded to angular 5 and this package no longer builds.

```
ERROR in ./node_modules/ngx-fill-height/index.ts
Module build failed: Error: /home/vagrant/app/node_modules/ngx-fill-height/index.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (/home/vagrant/app/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:677:23)
    at plugin.done.then (/home/vagrant/app/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
```

Not 100% sure how to resolve this but I'm doing some digging.

**Comment by bashoogzaad** [comment]
Any solution for this problem?

**Comment by jcollard** [comment]
I wasn't able to get this working. In the end, I stopped using this utility.

**Comment by jcollard** [comment]
The solution would involve fixing how the library is packaged.

**Comment by arthurvaverko-kaltura** [comment]
Im sorry .. i cant find the time to fix this .. if anyone wants to takeover this and repackage i'll be more than willing ..

**Comment by nop1984** [comment]
@arthurvaverko may be this helps [Complete beginner guide to publish an Angular library to npm](https://medium.com/@esanjiv/complete-beginner-guide-to-publish-an-angular-library-to-npm-d42343801660)
